[tool.poetry]
name = "biosim-verifier"
version = "0.0.1"
description = "A Biological Simulation Result Verification Service (bsrv)"
authors = ["Alex Patrie <alexanderpatrie@gmail.com>"]
readme = "README.md"
include = ["pyproject.toml"]
packages = [
    {include = "gateway"},
    {include = "worker"}
]


[tool.poetry.dependencies]
python = "^3.10"
requests-toolbelt = "^1.0.0"
seaborn = "^0.13.2"
toml = "^0.10.2"
requests = "^2.32.3"


[tool.poetry.group.dev.dependencies]
pip-autoremove = "^0.10.0"
pytest = "*"


[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "--ignore=setup.py"
python_files = "main.py"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

