[tool.poetry]
name = "bsvs-server"
version = "0.0.1"
description = "Server for the Biological Simulation Result Verification Service (bsvs)"
authors = ["Alex Patrie <alexanderpatrie@gmail.com>"]
readme = "README.md"
include = ["pyproject.toml"]
packages = [
    {include = "gateway"},
    {include = "shared"},
    {include = "tests"},
    {include = "worker"}
]


[tool.poetry.dependencies]
python = "^3.11"
pip-autoremove = "^0.10.0"
requests-toolbelt = "^1.0.0"
python-dotenv = "^1.0.1"
google-cloud-storage = "^2.19.0"
python-multipart = "^0.0.20"
fastapi = "^0.115.6"
toml = "^0.10.2"
typing-extensions = "^4.12.2"
pymongo = "^4.10.1"
pydantic-settings = "^2.7.0"
pydantic = "^2.10.4"
uvicorn = "^0.34.0"
pyyaml = "^6.0.2"
requests = "^2.32.3"
pytest = "^8.3.4"
numpy = "^2.2.1"
pandas = "^2.2.3"
h5py = "^3.12.1"
chardet = "^5.2.0"


[tool.poetry.group.worker.dependencies]
python-libsbml = "^5.20.4"


[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "--ignore=setup.py"
python_files = "main.py"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

