openapi: 3.1.0
info:
  title: bsvs-server
  version: 0.0.1
paths:
  /:
    get:
      summary: Root
      operationId: root__get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
  /verify:
    post:
      tags:
      - Verification
      summary: Compare UTC outputs from a deterministic SBML model within an OMEX/COMBINE
        archive.
      operationId: verify
      parameters:
      - name: simulators
        in: query
        required: false
        schema:
          type: array
          items:
            type: string
          description: List of simulators to compare
          default:
          - amici
          - copasi
          - pysces
          - tellurium
          - vcell
          title: Simulators
        description: List of simulators to compare
      - name: include_outputs
        in: query
        required: false
        schema:
          type: boolean
          description: Whether to include the output data on which the comparison
            is based.
          default: true
          title: Include Outputs
        description: Whether to include the output data on which the comparison is
          based.
      - name: observables
        in: query
        required: false
        schema:
          anyOf:
          - type: array
            items:
              type: string
          - type: 'null'
          description: List of observables to include in the return data.
          title: Observables
        description: List of observables to include in the return data.
      - name: comparison_id
        in: query
        required: false
        schema:
          anyOf:
          - type: string
          - type: 'null'
          description: Descriptive prefix to be added to this submission's job ID.
          title: Comparison Id
        description: Descriptive prefix to be added to this submission's job ID.
      - name: rTol
        in: query
        required: false
        schema:
          anyOf:
          - type: number
          - type: 'null'
          description: Relative tolerance to use for proximity comparison.
          title: Rtol
        description: Relative tolerance to use for proximity comparison.
      - name: aTol
        in: query
        required: false
        schema:
          anyOf:
          - type: number
          - type: 'null'
          description: Absolute tolerance to use for proximity comparison.
          title: Atol
        description: Absolute tolerance to use for proximity comparison.
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Body_verify'
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VerificationRun'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /get-output/{job_id}:
    get:
      tags:
      - Results
      summary: Get the results of an existing verification run.
      operationId: get-output
      parameters:
      - name: job_id
        in: path
        required: true
        schema:
          type: string
          title: Job Id
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VerificationOutput'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    Body_verify:
      properties:
        uploaded_file:
          type: string
          format: binary
          title: Uploaded File
          description: OMEX/COMBINE archive containing a deterministic SBML model
      type: object
      required:
      - uploaded_file
      title: Body_verify
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    Hdf5DataValues:
      properties:
        shape:
          items:
            type: integer
          type: array
          title: Shape
        values:
          items:
            type: number
          type: array
          title: Values
      type: object
      required:
      - shape
      - values
      title: Hdf5DataValues
    SimulatorRMSE:
      properties:
        simulator1:
          type: string
          title: Simulator1
        simulator2:
          type: string
          title: Simulator2
        rmse_scores:
          additionalProperties:
            type: number
          type: object
          title: Rmse Scores
      type: object
      required:
      - simulator1
      - simulator2
      - rmse_scores
      title: SimulatorRMSE
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
    VerificationOutput:
      properties:
        job_id:
          type: string
          title: Job Id
        timestamp:
          type: string
          title: Timestamp
        status:
          type: string
          title: Status
        omex_path:
          anyOf:
          - type: string
          - type: 'null'
          title: Omex Path
        requested_simulators:
          anyOf:
          - items:
              type: string
            type: array
          - type: 'null'
          title: Requested Simulators
        observables:
          anyOf:
          - items:
              type: string
            type: array
          - type: 'null'
          title: Observables
        sim_results:
          anyOf:
          - items:
              additionalProperties:
                $ref: '#/components/schemas/Hdf5DataValues'
              type: object
            type: array
          - type: 'null'
          title: Sim Results
        compare_results:
          anyOf:
          - items:
              $ref: '#/components/schemas/SimulatorRMSE'
            type: array
          - type: 'null'
          title: Compare Results
      type: object
      required:
      - job_id
      - timestamp
      - status
      title: VerificationOutput
    VerificationRun:
      properties:
        job_id:
          type: string
          title: Job Id
        timestamp:
          type: string
          title: Timestamp
        status:
          type: string
          title: Status
        omex_path:
          type: string
          title: Omex Path
        requested_simulators:
          items:
            type: string
          type: array
          title: Requested Simulators
        include_outputs:
          anyOf:
          - type: boolean
          - type: 'null'
          title: Include Outputs
          default: true
        observables:
          anyOf:
          - items:
              type: string
            type: array
          - type: 'null'
          title: Observables
        comparison_id:
          anyOf:
          - type: string
          - type: 'null'
          title: Comparison Id
        rTol:
          anyOf:
          - type: number
          - type: 'null'
          title: Rtol
        aTol:
          anyOf:
          - type: number
          - type: 'null'
          title: Atol
      type: object
      required:
      - job_id
      - timestamp
      - status
      - omex_path
      - requested_simulators
      title: VerificationRun
