---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-secret
  namespace: biosim-local
spec:
  encryptedData:
    .dockerconfigjson: AgCry5QuELowblrjjg1cO1EUNg+46LWNrXnhdVlMryIQezOhni48BFWL6gVOWyaxkbtGSQxnwMAWZSWwl6FLlMJvRdozh9aNZaDrTaPITtrsX/n83j2rb7ujUYLBdvWKEhyJTKGIFXBbol4+dnR0AJ2Uaz5x2vIEh++bQgwjXwsccpnW4BHKrIQImkacI7lDnYxCtNqLhOijE9k0A5hpmh4sCHJpxTph4FZGhie75ZscLrjwMinAUT8twB083OC7DqOlY0jzseMtCl+tLRqh89TdUWIhptcGq85PHMb309E87v2yvzkhkSGm+Psa1x4ahihrFraEjhzB1EdmAUt4Mj3TjrFCW8ZzJPGb/+PV0ltsRrA2OKVVT0ZbzPipQ02qQpqkcAzBj/V+jXEo3diEkUTYSi8Tdv+TL9qN9FLGYy0uKS6XeNPPMOAZFmbYGcmolO2EYcYpvYZ6VcTBTgGnhw9Hp2SPysqOF8VAZw5ocEBDdD9gKDN2IRcbQg3+ugmpeBuNWWXwmwMplMe3aI0WbRmgKZmgEvyya/Z3OKuNnJp2Q6j7JIARSDoRXMmkOaBwWnGcUoqcfx9V7E+0BA0lHVbVU9ZqUvUXB47ntiBrYL5JPGFQgCKATMd8hPMxkKg70XuDoE/WEHVI83MkSWVeRzEna562of95Hn8p8pF7Gry/+T44Ak9Ma/vRZOqz/UoB7lM9bZlc9GQYrFtUTEWSNPEp1QipjbCubbUN6LmLFy71bnKfB1zlHjyQqjr4uWmA/hyHgT3CNdlAk5Ej5BB8/fCSDEqHOTyFlxQBMirdEiCooQYtgWK9GRV5nKmRuBpmjJPhM7asmS8GENX8dO37H0c/6AIA6QDwvzuk9c3/czr7+kfYDLF4CNjtpFWH5oC7JPLAmcnOaPcX4cLq+aXYUlfECrjgYFEJggO8K4q+lAvAEyOopBQLxqyU274KU+ARm97cRNWfmO69UyDlNs/cwN6r
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-secret
      namespace: biosim-local
    type: kubernetes.io/dockerconfigjson
