---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-secret
  namespace: biosim-gke
spec:
  encryptedData:
    .dockerconfigjson: AgAwMXXXHJqCIQmmdoW64K7hbZuh8gbVx+TOEs2bSOOZvWVaZSsdaV9S97y1OFhPwv9Ik5KVgGkRHvesZ2AXkwkx5kVRNQoMXKNEuFMGKacxB0zxpXRahXcwvvMN8jEXYeVX3QJz+bw0XBG+aj76yFwsZdegTi7KPnPaTHniDQ8dhQwCQ9dncyvWwc4pulpk/n3RxVRtUC4xBvNT6o0ud14e/gvqKAvsM0cK56bdiZagODoiskxZA1gfCDnpW7p4tISTX91K1Oq+xcmQHrTHRo29uYIQ9z2zQswNkcV4MkqZ9P6ZEoGqs3+e7UfuVF+5YHE25kt646dLtPYlzjV21kytVcDZQfCRolDiik4nZIk5Fbn6W8kF1XQ+IUNwLTwVBXcIthw8Zd+FBj9g146WkJTSLBPxxjwjBSNGC0ZYOdKVn3ksMUUy01FRoU7N+Ibx7yMIDGR3r0D+GeQb0RhtIhD7ncwYaMBGzgYp8/lzblWV/vGKoloY+5URwum77hGh9U4UgsUmjhIrBOQicIUhoJwhCPD23Bt1UVimRRkfemlgEjOyTEZmztJJU3rbIvuaExJXrByMhDOCbxC6tTEfPFjk4vJLp1/6ntaYPT0G7kZpP8jNePjX7TAkS2xLuEIT1eRJnjX906zRNOV79F67mxWU9Foc8OYhBETzzY2Zlwtc0iRcFzHtJOkicdcKOkMKKu5k+8ECUNDA45MVl0UGhc/YFo7BtkYuXkWxi6QxJNscMlr2lT70jyVM6UnJMZnSIXpRkHKZAHCxZI4Hw/lbZoGsTACU2cXiI4zIx9fd99zryQ/HFInmdElDkboCJqwrYLewhy5oBXr2bkUl9Kf5d9dEoqy5SCXvezZ7557gr09xCGWvC3qpWIyCz/BgVQrNYp+V7JZjf5pQ9XujYlIRhsjkSpRVl3RkucOfftrWxhgf1uLsrnw6mugUiYH6VHG3+ldQ7qy5x+7hqk/3a3xCnvB9
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-secret
      namespace: biosim-gke
    type: kubernetes.io/dockerconfigjson
