---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-secret
  namespace: biosim-gke
spec:
  encryptedData:
    .dockerconfigjson: AgCuJt4HxwuWMpx78jMwBiWYxEvFWObwSsb7q1LDMt96UlFaLikAVThlHPl9bBDt8Nxq1dbl9tgtyFOou8X2dEycrqEuruthMca5ViGugl8AtVU3W6X1BplB9GPS1/rUn5YY7IdcnsgtBVc66fkP73+crUsOQ27psRwffaLbJjL5dDLDmK1I3cnWhOfnNQDCCXcJdkWP1M3vFNPQRjmyz4SZd/7LDvGoiUrRyrpaQ+y5DPQjNDAB+uotvl7kwSqgFoG2gAuR3/Dc71NNsAmswQP/fTeQr0W2cD/7O1Ju/Se1laSJ5ZxfAF8dfhv+73kj6JVpsahy6zKm5br8wFLYchur9DhzqLt1c/wyvGXgNKwNCu7yHCwXUNH7MKYss/xRGvpZYSNuxDM8nB6Wp9rzrKiqRfglBa6++NvMT8LtC+OBJhtHOPRzT6uj3buPKzsGrG1qBjhag83YuYxSSOnBhFg4qGqmg2aUuMtgps6nIqaVgTupHXS9MLegQnUH3gWDL8XJXOWmb3IM3cXkzbZmUWBMM+gTBtAtTSYXPM9Ii1Zl8q9KbxIIF+bPtnm6Jt/rtwidL2uQgmki0UMDq/1jU0NdzZUgBgJEECo9eT6WrZ5Hj7sTRStfSxs+GwhePYR71sd569JApKYYbR54ej9M5CPSxsWIaOMhxopiaVzgNcBeJ1l+c/bJo+GfUgm2wb+pC5sajGjH9oYXOP4ZoDAiNEsbyJrTQRbohw0veOWYsnTm1bwmxoIFj4KnuI41PlB5qzGbMrpBGEb71CLfTo+9KYlfkVWeKKp2FyyDNVk6qAluFkWrCUtaXSdH6/rsb6VTJbp45T6ai2mmVgZXLaLRnGLe6DhgvTc52pWYOj6cRs7B5u9ZdSe4lJbd/MfquwoF9xU/nUv6CkRTchKfuGGVIBnTsHGB83mghM/5rSP14OJHdIlTDQ4MuuiLlLxFh/Y8iwtms7akfn2ra+kW+OxuhM7N
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-secret
      namespace: biosim-gke
    type: kubernetes.io/dockerconfigjson
