---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: shared-secrets
  namespace: biosim-gke
spec:
  encryptedData:
    STORAGE_ACCESS_KEY_ID: AgCPWPXtiVFg3vfLbCtEfEKvW/SibQO99VXaTScIYzGsPrRITFRQWcn+yKU+YkN+vyXCkBFV+0nJ86NUos/XGLnbwaw/jxzR/UnnClI16o2bsJ7xOBK/nBbYf8PLVRgthFfTLHttC/i/v0ZJHmJOqwEN9kS/L7Cbjaa+OYWgv3zsKt7mnxgTn5NQvURLIzH6oSROdqGmM1ZWImBA6Jlda6LbVtMqxKPoL0kbjFcKAvDAlDsvil3P7qKQdoawgY24NSyypB/BGU+Exnwq0Kb8EgR99TXGtkhfabwnpUlkZ3HQfisS4CXg0xDiWUTsdrNvFctkHfBUshXLps6068Wt3CYdvev63rSYyP+oI7nJ9yQoyxPhpgPLiwRUqyPEPUp+RDznTSz58pPjcAKCHvg91JIvlTvWccF0jPqK7p/xgsTEHEAU2+qQj0rlAHnNmCBWc4z2gMQgAmhaxvNBgviqDpMUsyxBsv/O7InNHkL5txtGIp/I6U/9yhXGdixAklEPQ8+mtMiAmH95xUptjGqBV14tWjF/4TCAF2dE0HpD8afLC+hBIH6AxyqRe2gz2IU3BOBms3qS84ReIXsiWL9LjOUUpoRm5OKONLcotS2648U//WQ8vF8PcYvpF6XAFshjK1v0UYg3EMu+9bZov34txGlXmR8AyIGEsRzC5mU/zmYnYA57rtW0zqBNxN1mkvP79XW/AlIR1nULaRDEame4MpHDyhmE7atGiLNE1JhsFd5P6KjVCwDyhQwjxjSkBfAlKdk7zjEST+TzD0kt63xM
    STORAGE_SECRET: AgBmqsVJ3K8xc036Br/ANwjC/2+W6B2+3ERKWaxOVab+fEtdSsLuZzAT0I0s9g1s6fcHoBbi92PUVqhrL2GJWtz5vqIa94YhYOJnPJpiXkwiYRT4lqUIMR3RukMp1jDVBk/Ny/YZzDd5PDvJ9Nk/HQUtArwC5kSd24/as1J9knbt0qGJ9KiMau6I/07cuM09F72uiuRep0qmm2HzusPIAfQAhBUfuscokUFWapZ/272yNSRLiCkO5iqfLbpr/uNTs0bVQmU6gRTU29gJ+VQOEWxjoGJgZj42feQhj9OiRxYQwgUtbNj+V/k+2D/J2k9JNykA+UgZ3+dCsLHz+7N/p+A+dldYmgUkKbhsEyXlTsW+n3jvC799dK1IcfEe0gOUCqEXmZx8S5qImmteMCmEnrezEgLnU9zo4rlRj9gXVNIbIhO9rTSQR+v8ctZyo7Zs3JBPwjaZAWlxRd0UlZpepNb+2SIC6mjhqmS76QKTlJXx5vJPIXS/piuYKRhBtT0gPyzv5wj2WbJjzHiTcIBeagEWkVZP7Plsz6FwkSAn/sha/Dr4wR4aL/xpdyMhm7Xd6zaYORwAIPHVyUxBbIKkF5J/8pbuM3ISRWagcatp4Cg3f8mJ50mMcq7/KlR7n76MproQQfh46Rn368oXk3DNEXgRM3SSHJkYE00Kly8g8YEFbgMEwCqlQoJ5Vcb9PTuPoUqI7e092PdiZUeMtz92DWc7vnMgpt9Pzamsjh7M2WFLUDgaWeC8lxAQ
  template:
    metadata:
      creationTimestamp: null
      name: shared-secrets
      namespace: biosim-gke
