name: Test Microservice Builds

on:
  workflow_dispatch:

jobs:
  build-microservice-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Log in to GHCR
        run: echo "${{ secrets.REPO_ADMIN_GHCR_TOKEN }}" | docker login ghcr.io -u "${{ secrets.REPO_ADMIN_GH_USERNAME }}" --password-stdin

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r assets/pipeline/config/requirements.github.txt

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/compose/releases/latest | grep 'tag_name' | cut -d\" -f4)/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version  # Check if Docker Compose is installed correctly

      - name: Authorize Build Script
        run: sudo chmod +x ./assets/docker/scripts/build_microservice.sh

      - name: Test Gateway Build
        run: |
          ./assets/docker/scripts/build_microservice.sh gateway

      - name: Test Worker Build
        run: |
          ./assets/docker/scripts/build_microservice.sh worker
