# create kustimization.yaml file
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: biochecknet

images:
- name: mongo
  newTag: 8.0-rc
- name: ghcr.io/biosimulators/bsvs-server-gateway
  newTag: 0.0.1
- name: ghcr.io/biosimulators/bsvs-server-worker
  newTag: 0.0.1

replicas:
- count: 1
  name: biochecknet-api
- count: 1
  name: worker
- count: 1
  name: mongodb

resources:
- biochecknet-api-secrets.yaml
- mongodb-pvc.yaml
- secret-ghcr.yaml
- biochecknet-ingress.yaml
- ../../config/biochecknet
- ../../base

