apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: temporal

resources:
  - elasticsearch-claim0-persistentvolumeclaim.yaml
  - postgresql-claim0-persistentvolumeclaim.yaml
  - ../../base