---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: shared-secrets
  namespace: biosim-rke
spec:
  encryptedData:
    STORAGE_ACCESS_KEY_ID: AgCPN/sBHMHLhdXmR4RfmJ7QtRr3CdsTQoEutpzrcXdlWNlW5504GXo1zhmrYLEiKOtDGtgz3qkUakPelX+vY0fU6Xi+FCbKm/tSAkABIsGV5/8WrlQZkhm5QnC8j3oCEANYdVZRMj28Pgc/NM3UJ/Sj/8ukJcaJ6ybQbwsTCiunWdeQC1Hg9Qu4YWyfwumYUVS+bjqJQFaYej9fNTRNJlj2IP0QRNpRj0/oWEgeFOzfvGmSJ6hth/LVfHcTkKaucnpvpY3IkK039aHajsQGjWknpKYySrEcNh0QZIxbrZJUocxYFYu20uf/UaIt/0Fc2mv3zDnBj1muZMa2ipGb8uGw1eYoxdnnrmasMdUD5D2Rm/D50LoAs7xDTGEXJVFzFKo1btmH0CvsM7N2ey6OX2/xXP/1hnATfjp8hq2F0mReM5EDHeRoFyLITTFNssxqbWHtPm2MAGbFFvGAo9Cgrw8ifNsqjtvpAdyGaP9KeIIoyWot7HeV6vH6L7wLNkCmDp7mqdI5YNRLmKvM214DJrSVz3iWaMrpjfuF96OQNAiXWirA0R48u4AaDWpwPAtMF8UjT/t1cDH+PXl8JrRQIex3EAm2tKO4rLRnP/cb1+yFc7R5P3sM0qsEgMf9iX4d5VtaeD5/r/zN+NgKvY8MtQUUt+m6RFT1P2mSW5vCx6MNGXdMg0I4Q9UIn/fE/UeA2e003/+Rw8TZXLVP4wPvyhDfkEWxlhPwOirUE61H3xDkfrE3sKv4wcfKGfOn5aWp1WCuhWHK4ATqdqyoELJ4
    STORAGE_SECRET: AgACinyeH3/RSRKYx5cQZ/MNRsntp9tKQuca/udXQGwpRNv1s7VGv6VHkqvxUbGVkklCu6Oxv2Iba7MYW8D2L07edUPIO6QNI998lbs6u9INvaI8gIMbEpNhAvcKB6w113gO7kA324j4gU5avb95gdDuKkmth2n3+Dc8r9t4ldZ74xyav2odO2lyYAQ5ISjhGd+dkathOpiMX8f9KE41Hs8vGXNTMpRLd/f9fe82CBgNfIrWEofEnhhi0TRWqD2Ym+V6kg4zz9d+sSFMhrgENTjhbYyEb/DgYZBbTW+nXzSQ56Q9eiJDiMFIpmMCFmVEuO5mpk5VDp8dmU3S5RfWo5EastqnbBEY5FzXobqUS95O8YZ+X9c8fRw24MgDeFApB5SKwYTdzb9jW+v//6kuKJpv7rAzc60/LXxX6F+cmTmdfT3w3oadeWcqgV5qxBOsXzWOvY+uQFXrU1yTdNgNrjKAa22DFrZ5FauOHhBZdTUJS107eaOsuFiOEqw7uchGtn0LSS0sbn2Jk9OtN/XIO2r5Zqe6CDXj+8WyQdUElS5caqG8B2q3O+4rYV84Ye5QoKB8TK5DUqYMrqWWH9SWv4kGBdIAn1x907I5U4lSnBVapR0aWriJwBsCg2WLNX/5Gb3sOS806QlVW5iocPYWLGInQRCcFu/4wq6Lnqctmnyc4KW8bIq2NlAU0en5EUyLxvOzeQTCYgiOew16Mpjv1bsN4i94bFQF8LdPRagFBm9TsXbOmb9G+NBa
  template:
    metadata:
      creationTimestamp: null
      name: shared-secrets
      namespace: biosim-rke
