apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  labels:
    app: worker
spec:
  replicas: 3
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: ghcr.io/biosimulations/biosim-worker:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: worker-config
          env:
            - name: STORAGE_GCS_CREDENTIALS_FILE
              value: /app/secret/gcs-credentials.json
          volumeMounts:
            - name: gcs-credentials
              mountPath: /app/secret
              readOnly: true
            - name: worker-cache-pvc
              mountPath: /app/scratch
      volumes:
        - name: worker-cache-pvc
          persistentVolumeClaim:
            claimName: worker-cache-pvc
        - name: gcs-credentials
          secret:
              secretName: shared-secrets
              items:
                - key: gcs_credentials.json
                  path: gcs-credentials.json
      imagePullSecrets:
        - name: ghcr-secret
